// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCKbgTrG-RFiGdNLDbR-_NNrFg1cEp_294',
    appId: '1:103667654031:web:c642bfb38d83f91c8cfffa',
    messagingSenderId: '103667654031',
    projectId: 'zaid-point-of-sale',
    authDomain: 'zaid-point-of-sale.firebaseapp.com',
    storageBucket: 'zaid-point-of-sale.firebasestorage.app',
    measurementId: 'G-5QXYLBSC5C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCXeYaUiVMUQGA_1o6JeRMHAUgLUI5FrCM',
    appId: '1:103667654031:android:33db69a9ce08a97e8cfffa',
    messagingSenderId: '103667654031',
    projectId: 'zaid-point-of-sale',
    storageBucket: 'zaid-point-of-sale.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAnOeA3HBLjUy3oqRX1Uif-9ORS73oGsJM',
    appId: '1:103667654031:ios:1162c68b82c5f79c8cfffa',
    messagingSenderId: '103667654031',
    projectId: 'zaid-point-of-sale',
    storageBucket: 'zaid-point-of-sale.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAnOeA3HBLjUy3oqRX1Uif-9ORS73oGsJM',
    appId: '1:103667654031:ios:1162c68b82c5f79c8cfffa',
    messagingSenderId: '103667654031',
    projectId: 'zaid-point-of-sale',
    storageBucket: 'zaid-point-of-sale.firebasestorage.app',
    iosBundleId: 'com.example.pos',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyCKbgTrG-RFiGdNLDbR-_NNrFg1cEp_294',
    appId: '1:103667654031:web:31e3dcf1924f53ae8cfffa',
    messagingSenderId: '103667654031',
    projectId: 'zaid-point-of-sale',
    authDomain: 'zaid-point-of-sale.firebaseapp.com',
    storageBucket: 'zaid-point-of-sale.firebasestorage.app',
    measurementId: 'G-JELTQ922KH',
  );
}
